//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class CLASSROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASSROOM()
        {
            this.SUBJECTs = new HashSet<SUBJECT>();
            this.MAKEUP_LESSON = new HashSet<MAKEUP_LESSON>();
        }
    
        public int ID { get; set; }
        [DisplayName("Cố vấn học tập")]
        public Nullable<int> ID_TEACHERCONSULTANCY { get; set; }
        [DisplayName("Tên lớp")]
        public string NAME { get; set; }
        [DisplayName("Khóa")]
        public Nullable<int> COURSE { get; set; }
    
        public virtual TEACHER TEACHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBJECT> SUBJECTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAKEUP_LESSON> MAKEUP_LESSON { get; set; }
    }
}
