//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class FILE_NOTIFICATION
    {
        public int ID { get; set; }
        public Nullable<int> ID_NOTIFICATION { get; set; }
        public string TITLE { get; set; }
        public string NAME_FILE { get; set; }
    
        public virtual NOTIFICATION NOTIFICATION { get; set; }
    }
}
