//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class IMAGES_NEW
    {
        public int ID { get; set; }
        public Nullable<int> ID_NEWS { get; set; }
        public Nullable<int> ID_IMAGES_NEW_TYPE { get; set; }
        public string IMAGES { get; set; }
        public string IMAGES_ALT { get; set; }
    
        public virtual NEWS NEWS { get; set; }
        public virtual IMAGES_NEW_TYPE IMAGES_NEW_TYPE { get; set; }
    }
}
