//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeacherWorkEntities : DbContext
    {
        public TeacherWorkEntities()
            : base("name=TeacherWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IMAGES_NEW> IMAGES_NEW { get; set; }
        public virtual DbSet<IMAGES_NEW_TYPE> IMAGES_NEW_TYPE { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<FILE_NOTIFICATION> FILE_NOTIFICATION { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATIONs { get; set; }
        public virtual DbSet<ARRANGE_TIME_SLOT> ARRANGE_TIME_SLOT { get; set; }
        public virtual DbSet<CLASSROOM> CLASSROOMs { get; set; }
        public virtual DbSet<DAY> DAYs { get; set; }
        public virtual DbSet<ROOM> ROOMs { get; set; }
        public virtual DbSet<TEACHER_TYPE> TEACHER_TYPE { get; set; }
        public virtual DbSet<TIME_SLOT> TIME_SLOT { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<TEST_SCHEDULE> TEST_SCHEDULE { get; set; }
        public virtual DbSet<TEACHER> TEACHERs { get; set; }
        public virtual DbSet<ACADEMIC_RANK> ACADEMIC_RANK { get; set; }
        public virtual DbSet<SUBJECT> SUBJECTs { get; set; }
        public virtual DbSet<MAKEUP_LESSON> MAKEUP_LESSON { get; set; }
        public virtual DbSet<APPLICATION_LEAVE> APPLICATION_LEAVE { get; set; }
    }
}
